name: lomenu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  firebase_core: ^2.1.1
  flutter_riverpod: ^2.0.2
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  dotted_line: ^3.1.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.6
  path_provider: ^2.0.11
  image_picker: ^0.8.6

dev_dependencies:
  flutter_native_splash: ^2.1.3+1
  flutter_launcher_icons: ^0.10.0

flutter_native_splash:
  color: '#ffa500'
  image: 'assets/LOmenu-icon.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffa500'
    image: 'assets/LOmenu_splash4.png'
    fullscreen: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOmenu-icon.png"


  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/a.png
    - assets/test_image.jpg
    - assets/LOmenu-icon.png
    - assets/LOmenu_splash4.png
    - assets/LOmenu_gurahu.png
    - assets/mypage_food_image.jpg
    - assets/image_picker1116821702790665454.jpg
    - assets/image_picker1134667383066571979.jpg

    - assets/lomenu-food/lomenu-1-1-onion.jpeg
    - assets/lomenu-food/lomenu-1-2-potato.jpeg
    - assets/lomenu-food/lomenu-1-3-carrot.jpeg
    - assets/lomenu-food/lomenu-1-4-cabbage.png
    - assets/lomenu-food/lomenu-1-5-Chinese-cabbage.jpeg
    - assets/lomenu-food/lomenu-1-6-piman.png
    - assets/lomenu-food/lomenu-1-7-tomato.jpeg
    - assets/lomenu-food/lomenu-1-8-cucumber.jpeg
    - assets/lomenu-food/lomenu-1-9-japanese-white-radish.jpeg
    - assets/lomenu-food/lomenu-1-10-eggplant.jpeg
    - assets/lomenu-food/lomenu-1-11-pumpkin.jpeg
    - assets/lomenu-food/lomenu-1-12-japanese-leek.jpeg
    - assets/lomenu-food/lomenu-1-13-ginger.png
    - assets/lomenu-food/lomenu-1-14-garlic.png
    - assets/lomenu-food/lomenu-1-15-broccoli.jpeg
    - assets/lomenu-food/lomenu-2-1-tori-momo.png
    - assets/lomenu-food/lomenu-2-2-tori-mune.png
    - assets/lomenu-food/lomenu-2-3-tori-sasami.png
    - assets/lomenu-food/lomenu-2-4-buta-komagire.png
    - assets/lomenu-food/lomenu-2-5-buta-rousu.png
    - assets/lomenu-food/lomenu-2-6-buta-momo.png
    - assets/lomenu-food/lomenu-2-7-buta-bara.png
    - assets/lomenu-food/lomenu-2-8-buta-hire.png
    - assets/lomenu-food/lomenu-2-9-usi-komagire.png
    - assets/lomenu-food/lomenu-2-10-usi-rousu.png
    - assets/lomenu-food/lomenu-2-11-usi-momo.png
    - assets/lomenu-food/lomenu-2-12-usi-bara.png
    - assets/lomenu-food/lomenu-2-13-usi-hire.png
    - assets/lomenu-food/lomenu-2-14-hikiniku-chicken.png
    - assets/lomenu-food/lomenu-2-15-hikiniku-pork.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
